apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}-frontend
  labels: {{- include "frontend.labels.standard" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - port: {{ .Values.frontend.service.port }}
    targetPort: http
  selector: {{- include "frontend.labels.matchLabels" . | nindent 4 }}
